Logger:
  Level: -4


HTTPServer:
  Port: 8080
  ReadTimeout: 10s
  ReadHeaderTimeout: 500ms
  WriteTimeout: 10s
  IdleTimeout: 1s
  MaxHeaderBytes: 500
  ShutdownTimeout: 5s
  TestPass: password 
  

DataBase:
  DBFile: /app

